# ANN Foundations

## Perception Training Using Error-Corrective Learning

### Functional Output Of Perception

$$ y = \sum(x_i * w_i) $$

In [29]:
import numpy as np

In [30]:
# output function

def functional_output(inputs, weights):
    return np.dot(inputs, weights)

In [31]:
functional_output([1,2],[3,4])

11

In [32]:
# activation output

def activation_otuput(output, threshold):
    if output >= threshold:
        return 1
    else:
        return 0

In [33]:
activation_otuput(11, 3)

1

$$ e = g -f $$

In [34]:
def error(activation, expected):
    assert len(activation) == len(expected), 'Dimension do not match'
    return np.subtract(expected, activation)

In [35]:
error([3,2],[1,1])

array([-2, -1])

In [36]:
def update_weight(x, error, learning_rate):
    return x * error * learning_rate

In [37]:
weight = update_weight(1,2,1)

In [38]:
weight

2

In [39]:
class SimpleNN:
    
    training_data = np.array([[-1, 1, 1, 1],
                             [-1, 1, 0, 1],
                             [-1, 0, 1, 1],
                             [-1, 0, 0 ,0]])
    
    weights = np.array([0, 0, 1])
    
    learning_rate = 1
    
    threshold = 1
    
    input_data = training_data[:, [0, 1, 2]]
    
    desired_output = training_data[:, [3]].T[0]

In [40]:
snn = SimpleNN()

print(snn.training_data)
print(snn.weights)
print(snn.learning_rate)
print(snn.threshold)
print(snn.input_data)
print(snn.desired_output)

[[-1  1  1  1]
 [-1  1  0  1]
 [-1  0  1  1]
 [-1  0  0  0]]
[0 0 1]
1
1
[[-1  1  1]
 [-1  1  0]
 [-1  0  1]
 [-1  0  0]]
[1 1 1 0]


In [41]:
y = np.array(functional_output(snn.input_data, snn.weights))
print(y)

[1 0 1 0]


In [42]:
fy = np.array([activation_otuput(o, snn.threshold) for o in y])
print(fy)

[1 0 1 0]


In [43]:
err = error(fy, snn.desired_output)

print(err)

[0 1 0 0]


In [53]:
# Algorithm For Training Using Error-Corrective Learning

w = snn.weights

counter = 0

while not np.array_equal(snn.desired_output, fy):

    print("Epoch", np.round(counter%4))
    
    print("weights            input          desired_output         actual_output        error        new_weight")
    
    for x in snn.input_data:
        
        y = np.array(functional_output(x, w))
        
        fy = np.array([activation_otuput(o, snn.threshold) for o in y])
        
        err = error(fy, snn.desired_output)
        
        if err[counter%4] == 0 :
            print(w, "\t", x, "\t", snn.desired_output[counter%4],
                  "\t\t\t", fy[counter%4], "\t\t", err[counter%4], "\t", w, "no change")
        
        else:
            print(w, "\t", x, "\t", snn.desired_output[counter%4], "\t\t\t", fy[counter%4], "\t\t", err[counter%4], "\t", w, "update weights")
            
            w = w + update_weight(snn.input_data[counter%4], err[counter%4], snn.learning_rate)
            
        counter += 1
        
    
print(snn.training_data)
print(snn.weights)
print(snn.learning_rate)
print(snn.threshold)
print(snn.input_data)
print(snn.desired_output)